openapi: 3.0.0
servers:
  - url: 'http://petstore.swagger.io/v2'
info:
  description: >-
    This is a sample server Petstore server. For this sample, you can use the api key
    `special-key` to test the authorization filters.
  version: 1.0.0
  title: OpenAPI
tags:
  - name: user
    description: Operations about user
paths:
  /user:
    $ref: './endpoints/users.yaml'
