version: "3.9"  # optional since v1.27.0
services:
  mysql:
    image: mysql:5.7
    environment:
        MYSQL_ALLOW_EMPTY_PASSWORD: "true"
        MYSQL_DATABASE: "testdb"
    command: "mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci"
    ports:
      - "3306:3306"
